var age = 23;
console.log("dev: age", age);
age = true;
console.log("dev: age", age);
age = "dsdsv";
console.log("dev: age", age);
age = { name: "manoj " };
console.log("dev: age", age);
var mixed = [];
mixed.push("dsvsd");
mixed.push(true);
mixed.push(12);
console.log(mixed);
var ninja;
ninja = { name: "dsvs", age: "fvds" };
console.log("dev: ninja", ninja);
